// Cloudflare Worker bindings — generated by `npm run types`
// Update after creating D1/KV: npm run types

export interface Env {
  // D1 Database
  DB: D1Database

  // KV: rate limit counters (ip:hash:date → count, ttl 86400)
  RATE_KV: KVNamespace

  // Secrets (set via: wrangler secret put KEY)
  BETTER_AUTH_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  YOUTUBE_API_KEY: string  // public key for channels.list polling

  // Vars
  ENVIRONMENT: 'development' | 'production'
  APP_URL: string
  YOUTUBE_QUOTA_PROJECT: string
}
